Mobile version skeleton
Christabelle143/mobile-version pull request #1
Opened 2022-03-21 21:19 UTC by Christabelle143

### In this milestone I did the following:

- Add a header and a headline section in the index.html file which I created.
- Add stylings to the header and headline section in the style.css file.
- Modified and updated my README.md file using the template provided.
- Add the images folder with images downloaded from the first Figma template.

2022-03-21 22:13 UTC, BenMukebo requested changes
### Hi ** @Christabelle **

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/8rEVuWu3BLB9VHj9F9/giphy-downsized-medium.gif"/>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


- [ ] Kindly, Add a descriptive README file to your project as required please use this [template](https://github.com/microverseinc/readme-template) You can copy past but remember to customize it to your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 22:13 UTC, BenMukebo commented on index.html
> +    </div>
- [ ] let dive into your design now, please take a look at this image below compared to the original design.
   - your intro title is not using the same font and color as the original one
   - please adjust your padding and margin to make some few spaces around the `let connect` text.
   - right at the bottom left, please refer to the Figma template to do what is supposed to be there, you should crop that corner as shown with the red line.
   
<img width="289" alt="b" src="https://user-images.githubusercontent.com/79058364/159371554-8260c502-a286-4cd5-9079-68efd38bb785.png">

- [ what it should look like ]
<img width="236" alt="bela fig" src="https://user-images.githubusercontent.com/79058364/159371595-06c70e70-d8c9-4d67-9615-b30b60f65ac9.png">

2022-03-23 12:50 UTC, Christabelle143 commented
Hi, **@BenMukebo** 
The image I got from the Figma template is a full one and I also find difficulties in cropping the picture to get the edges like the one you showed above. Don't know how to get it done

2022-03-23 13:29 UTC, BenMukebo commented
Hello @Christabelle143, you can use border-radius on that specific corner

2022-03-23 15:48 UTC, Christabelle143 commented
Hi, ** @BenMukebo** 
I have tried the border-bottom-right-radius to no avail. It's not working. And I don't know why.

2022-03-23 17:33 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Christabelle143👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 17:33 UTC, thecodechaser commented on index.html
> +            </a>
- [ ] As requested by the previous reviewer, Please remove the logo from the `<nav>` tag and just keep it in the header tag directly. The header is not part of our navbar so it is not good practice to place it inside `<nav>`
- [ ] Please remove `<h2>` inside anchor tag, It's not good practice to place headings inside an anchor tag, You can place the text directly inside the anchor tag.

2022-03-23 17:33 UTC, thecodechaser commented on index.html
> +                website Look through some of my work and experience! If you like what
- [ ] The background images are overflowing the content and the design is not looking good, Please fix the background images and make sure it matches the design on the [template ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)to make the project looks more professional.

### Your design

![image](https://user-images.githubusercontent.com/83803414/159760486-1ee8b40d-0b40-4d12-8604-a076522a98b5.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/159760749-093df27a-3216-4ade-81e3-b43ff9b90e56.png)

2022-03-24 00:11 UTC, merged