Add work and about section
Christabelle143/mobile-version pull request #2
Opened 2022-03-25 20:48 UTC by Christabelle143

**In this section of the project I**;

-   Added the work section using the HTML and CSS file I used for both the header section.
-   Added the about section using the HTML and CSS file I  used for both the header section.

2022-03-25 21:45 UTC, prolajumokeoni requested changes
Hi @Christabelle143 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description



## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 21:45 UTC, prolajumokeoni commented on index.html
> +        <section class="workcontainer">
- [ ] kindly add `display:grid` to the main container of the projects instead of flex as this is part of the project requirement
- [ ] Please add the button styling when the button is Active, Hovered or Pressed in each project card 👍🏿 

![Screenshot_4](https://user-images.githubusercontent.com/69638013/160200908-bd4b55bf-b1eb-4a8e-b69c-7232c54c65c1.png)

2022-03-25 21:45 UTC, prolajumokeoni commented on index.html
> +                    </h1>
- [ ] Kindly change this hx tag to any header tag from h2 - h6, because your page should have only one h1 tag 👍🏿

2022-03-25 21:45 UTC, prolajumokeoni commented on index.html
> +
- [ ] Please add the button styling when the button is Active, Hovered or Pressed  for the let's connect link 👍🏿

2022-03-26 00:21 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @Christabelle143,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-26 00:23 UTC, merged