Created_work_about_section
Christabelle143/mobile-version pull request #2
Opened 2022-04-19 10:57 UTC by Christabelle143

# In this project, i;
-Added the work and about section for my personal portfolio project.
-Created an index.html and style.css file for both the HTML and CSS codes used for this project respectively.
-Added linters file to check for linters errors in the codes.
-Downloaded some images from the Figma template for the project's design.

2022-04-19 12:01 UTC, codepantha requested changes
Hi @Christabelle143 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

You have done a terrific job so far! 👏 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

### To Highlight 🎯 
- Nice UI ✅ 
- Meaningful commit messages ✅ 
- Descriptive PR ✅ 
- Linter checks ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 12:01 UTC, codepantha commented on index.html
> +                        </li>
- [ ] This icon does not display. Kindly fix it 🙏 
![image](https://user-images.githubusercontent.com/46839548/163995083-1002ffec-02d6-4542-a578-67ddd362f71f.png)

2022-04-19 12:01 UTC, codepantha commented on style.css
> +  }
- [ ] I noticed that the `.about-description` takes up only a portion of the screen at screen sizes of `425px` to `768px` which is at odds with the given design. Please take a look and modify it. 👍 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/163997624-bb7e17fb-d923-4a8d-b469-5d9b24b511ae.png)


### Figma Design
![image](https://user-images.githubusercontent.com/46839548/163997244-f90ab09d-3dc5-4b60-a172-a3b59680f2ef.png)

2022-04-19 12:01 UTC, codepantha commented on index.html
> +                    </ul>
- [ ] The dropdown menu containing a list of the technologies only take up a chunk of the screen which is at odds to the given design template. Please take a look below and fix it 👇 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/163998194-51fd2cdd-c462-4354-84fb-440c510104ab.png)

### Figma Design
![image](https://user-images.githubusercontent.com/46839548/163998260-2cd31f53-21c4-47cd-9b0c-4847f4b6cffb.png)

2022-04-19 15:19 UTC, Christabelle143 commented on index.html
> +                        </li>
Hello @codepantha 
Thanks for the review, but can't get why this LinkedIn icon doesn't show on your browser while it's displaying on my page. Have tried checking it but it seems to be working don't know why it's not working on your browser

2022-04-19 15:39 UTC, codepantha commented on index.html
> +                        </li>
It might have been from my end @Christabelle143
Please fix all the other issues I highlighted and ask for another review. Good luck 😎

2022-04-20 15:59 UTC, Christabelle143 commented on index.html
> +                    </ul>
Hey @codepantha,
I'm having issues resolving this issue of the content not taking up part of the screen within the range of 425 and 768.
When I try increasing the width of the contents the work just becomes messy. Thought of removing the @media only screen and (max-width: 768px){} property from the style.css file but don't know if that's a good idea. Please can you give me more hints on how to solve this issue??.

2022-04-21 08:31 UTC, Christabelle143 commented on index.html
> +                    </ul>
Hey @codepantha 
please am still waiting for your reply

2022-04-21 10:37 UTC, m05e5 commented on index.html
> +                    </ul>
Hi @Christabelle143

2022-04-21 10:39 UTC, Christabelle143 commented on index.html
> +                    </ul>
yes @m05e5

2022-04-21 10:40 UTC, m05e5 commented on index.html
> +                    </ul>
Don't bother the layout of your mobile design is perfectly fine you did a Great job 👍.

2022-04-21 10:41 UTC, Christabelle143 commented on index.html
> +                    </ul>
hello @m05e5

2022-04-21 10:43 UTC, m05e5 approved these changes
# Hi @Christabelle143 , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You really did a great job. You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[Highly Recommended]

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 10:45 UTC, Christabelle143 commented on index.html
> +                    </ul>
Oh thanks so much

2022-04-21 10:49 UTC, merged

2022-04-21 12:44 UTC, m05e5 commented on index.html
> +                    </ul>
Yes, any issue?

2022-04-21 12:46 UTC, m05e5 commented on index.html
> +                    </ul>
Yes @Christabelle143  any issue?

2022-04-21 13:18 UTC, codepantha commented on index.html
> +                    </ul>
Hi @Christabelle143
Sorry I missed this question 🙏 . Though your PR has been approved, but I'd consider it a great idea to remove the 
```
@media only screen and (max-width: 768px){}
```
 media query since we're building mobile-first.

When you start building the desktop version you'd then use 
```
@media only screen and (min-width: 768px){}
```