Added Contact Section
Christabelle143/mobile-version pull request #3
Opened 2022-03-29 18:35 UTC by Christabelle143

# In this pull request my coding partner and I;

- Added the contact section for the mobile portfolio project by adding HTML codes in the index.html file.
- Styled the contact section by adding CSS stylings in the style.css file for the portfolio project.
- Added a background image for the contact section to make it look user friendly and attractive.

2022-03-29 18:59 UTC, Donard97 requested changes
## Hello TEAM  , 👋  

_You did an amazing job on adding the contact from of your portfolio so far! 👏 💯_ 

**_There are some issues that you still need to work on to go to the next project but you are almost there! 💪_** 

![giphy (5)](https://user-images.githubusercontent.com/74506933/160684977-40d57f17-77aa-4f3d-ae23-9af8fd055d36.gif)

## Highlights 🏁 ✅ 

✔️ The Readme is professional
✔️ Code is clean
✔️ Gitlow is used correctly
✔️  PR is descriptive

## Required Changes ♻️

- [ ] Please check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-29 18:59 UTC, Donard97 commented on index.html
> +                <p class="contact_description">
- [ ] You did an amazing job adding the contact form and styling it but kindly decrease the height of the section and fix the background because as it was part of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md) you must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Keep coding 💪 

Here is a screenshot from your project:

![image](https://user-images.githubusercontent.com/74506933/160684274-c056e9b2-2c23-43b1-903c-6a77901475a6.png)

Here you have a screenshot from the design:

![image](https://user-images.githubusercontent.com/74506933/160684335-90628a70-8c08-4762-a48a-dca78f395128.png)

2022-03-30 00:17 UTC, nicupop729 requested changes
# Status: Required Changes ♻️

Hi @Christabelle143 & @Ghilain, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)
 ### Required Changes ♻️

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 00:17 UTC, nicupop729 commented on index.html
> +                <p class="contact_description">
@Christabelle143, congratulation on being the best!
You are doing great! :1st_place_medal: 

But our app looks now a bit ununiform:
Our design:
![image](https://user-images.githubusercontent.com/83596135/160726009-bfeddd1b-5074-46f4-91f8-35e5d2b70642.png)
A part is because of the display: grid, a part is from the padding of the inputs etc.

- [ ] Please take another close look at this part of the project, as we want it to be top-nought; :+1: 
 
Resubmit when ready :confetti_ball:

2022-03-30 10:14 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Christabelle143,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 12:19 UTC, merged